# This rule is not used by the project automatedappdeployment-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over automation.local.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: automatedappdeployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: automatedappdeployment-admin-role
rules:
- apiGroups:
  - automation.local.io
  resources:
  - automatedappdeployments
  verbs:
  - '*'
- apiGroups:
  - automation.local.io
  resources:
  - automatedappdeployments/status
  verbs:
  - get
