---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - automation.local.io
  resources:
  - automatedappdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.local.io
  resources:
  - automatedappdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - automation.local.io
  resources:
  - automatedappdeployments/status
  verbs:
  - get
  - patch
  - update
